# Generated by Django 4.2.3 on 2023-11-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('type_of_vehicle', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('year_of_purchase', models.IntegerField()),
                ('kilometers', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('registered_state', models.CharField(max_length=2)),
                ('number_of_owners', models.IntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_of_payment', models.CharField(max_length=50)),
            ],
        ),
    ]
