# Generated by Django 4.2.3 on 2023-11-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_No', models.CharField(max_length=20)),
                ('Departure_Time', models.DateTimeField()),
                ('Destinations', models.CharField(max_length=200)),
                ('Seats_Available', models.IntegerField()),
                ('TicketCosts', models.CharField(max_length=200)),
            ],
        ),
    ]
